"""

SOLO SE PUEDEN MODIFICAR LOS VALORES
¡NO CAMBIAR LOS NOMBRES!

"""

# CACHE SETTINGS
CACHE_SETTINGS = {
    "FILE_NAME" : "CacheDebug.pkl",
    "FILE_DEATH_DAYS" : 15,
    "ITEM_DEATH_TIME_DAYS" : 2,
    "ITEM_DEATH_TIME_HOURS" : 0,
}

SEARCH_SETTINGS = {
    "MAX_RESULTS_PER_ENGINE" : 8
}
